# 通过在服务器上构建去部署
version: '3.8'

services:
  luozhuohua:
    build: ./luozhuohua
    container_name: luozhuohua
    ports:
      - "8081:80"
    networks:
      - vue-network

  luozhuohua2:
    build: ./luozhuohua2
    container_name: luozhuohua2
    ports:
      - "8082:80"
    networks:
      - vue-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge