version: '3.8'

services:
  luozhuohua:
    build: ./luozhuohua
    container_name: luozhuohua
    ports:
      - "8080:80"
    volumes:
      - ./luozhuohua/dist:/usr/share/nginx/html/luozhuohua
    networks:
      - vue-network

  luozhuohua2:
    build: ./luozhuohua2
    container_name: luozhuohua2
    ports:
      - "8081:80"
    volumes:
      - ./luozhuohua2/dist:/usr/share/nginx/html/luozhuohua2
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge